// <auto-generated />
namespace CadastroUsuarios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SincronizacaoManual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SincronizacaoManual));
        
        string IMigrationMetadata.Id
        {
            get { return "202604072156580_SincronizacaoManual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
